### ISSUE TITLE
テストスイートとCI/CD設定の追加

### ISSUE THREAD

**Issue by seitamuro** [seitamuro/commit-message-generator#7]
# テストスイートとCI/CD設定の追加

## 現状の問題点
リポジトリには現在、自動テストやCIパイプラインが設定されていません。これにより、コード変更の品質保証が手動のみに依存しており、変更が既存機能を壊さないことを確認するのが難しくなっています。

## 改善案
以下の要素を含むテスト環境とCI/CD設定を追加することを提案します：

1. **Bashスクリプトのテスト**
   - [BATS](https://github.com/bats-core/bats-core) (Bash Automated Testing System)を使用したユニットテスト
   - モックを使用したAWS API呼び出しのテスト

2. **エンドツーエンドテスト**
   - 実際のGitリポジトリにフックをインストールし、コミットを作成するテスト
   - 出力されるコミットメッセージのフォーマット検証

3. **CI/CD設定**
   - GitHub Actionsワークフローの追加
   - プルリクエスト時の自動テスト実行
   - マージ時の自動リリース作成

### BATSテスト例
```bash
#!/usr/bin/env bats

setup() {
  # テスト用の一時Gitリポジトリを作成
  export TEMP_DIR=$(mktemp -d)
  cd $TEMP_DIR
  git init
  cp /path/to/commit-msg .git/hooks/
  chmod +x .git/hooks/commit-msg
  cp /path/to/generate_commit_message.sh .git/hooks/
  chmod +x .git/hooks/generate_commit_message.sh
}

teardown() {
  # テスト後のクリーンアップ
  rm -rf $TEMP_DIR
}

@test "正しいフォーマットのコミットメッセージが生成される" {
  # テストファイルの作成
  echo "test content" > testfile.txt
  git add testfile.txt
  
  # AWS APIのモック
  function aws() {
    echo '{"output": {"message": {"content": [{"text": "✨ add: テストファイルの追加\n\n- テスト用のファイルを作成しました"}]}}}'
  }
  export -f aws
  
  # コミット実行
  run git commit -m "Test commit"
  
  # 生成されたメッセージの検証
  local commit_msg=$(git log -1 --pretty=%B)
  [ "$commit_msg" = "✨ add: テストファイルの追加

- テスト用のファイルを作成しました" ]
}
```

### GitHub Actionsワークフローの例
```yaml
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up test environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bats
          
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Run tests
        run: bats tests/
        
  release:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            commit-msg
            generate_commit_message.sh
```

これらのテスト・CI設定の追加により、開発プロセスの品質が向上し、将来の変更による予期せぬ動作変更のリスクを減らすことができます。
